[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dimitra_cropyield_protocol_log_memo = "2K4ZWngrtJCt1CEiggxfBag6h2jVP8V4Gp8Vc3wrDMqU"
dimitra_deforestation_protocol_log_memo = "E22mM2hSBAb786m9c9mfdgCopdHVaXqeGF8fuNC7rgFJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
